### ISSUE TITLE
Where the superset_config.py file ? 

### ISSUE THREAD

**Issue by Jaykin001** [anilkulkarni87/airflow-docker#2]
--------------------------------------------------------------------------------
superset_1           |                                     WARNING
superset_1           | --------------------------------------------------------------------------------
superset_1           | A Default SECRET_KEY was detected, please use superset_config.py to override it.
superset_1           | Use a strong complex alphanumeric string and use a tool to help you generate 
superset_1           | a sufficiently random sequence, ex: openssl rand -base64 42
superset_1           | --------------------------------------------------------------------------------
superset_1           | --------------------------------------------------------------------------------

**Comment by anilkulkarni87** [comment]
@Jaykin001 I have updated the yaml file to include a superset secret key and it works fine now.
